# Generated by Django 4.0.3 on 2022-04-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_helper_remove_user_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
